baseURL: 'https://m-sahebi.github.io/'
theme: PaperMod
defaultContentLanguage: en

menu:
#  main:
#    - identifier: categories
#      name: categories
#      url: /categories/
#      weight: 10
#    - identifier: tags
#      name: tags
#      url: /tags/
#      weight: 20
#    - identifier: search
#      name: search
#      url: /search/
#      weight: 10

languages:
  fa:
    languageName: Persian
    languagedirection: rtl
    title: محمود صاحبی
    author: محمود صاحبی
    weight: 1
    keywords:
      [
        mahmoud sahebi,
        sahebi,
        محمود صاحبی,
        صاحبی,
        وبلاگ,
        نمونه کار,
        آموزش,
        برنامه نویسی,
        فرانت‌اند,
        سفارش,
      ]
    description: 'برنامه‌نویس و توسعه‌دهنده فرانت‌اند'
    label:
      text: '‌'
      icon: icon.svg
      iconHeight: 35
    profileMode:
      enabled: true
      title: محمود صاحبی
      subtitle: 'Frontend Developer'
      imageUrl: 'me.jpg'
      imageWidth: 160
      imageHeight: 160
      imageTitle: محمود صاحبی
      buttons:
        # - name: بلاگ
        #   url: posts
        - name: درباره من
          url: about
  en:
    languageName: English
    description: 'Frontend Developer'
    title: Mahmoud Sahebi
    author: Mahmoud Sahebi
    weight: 2
    keywords: [mahmoud sahebi, sahebi, blog, portfolio, frontend, developer]
    label:
      text: '‌'
      icon: icon.svg
      iconHeight: 35
    profileMode:
      enabled: true
      title: Mahmoud Sahebi
      subtitle: 'Frontend Developer'
      imageUrl: 'me.jpg'
      imageWidth: 160
      imageHeight: 160
      imageTitle: Mahmoud Sahebi
      buttons:
        - name: About
          url: about

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  images: []
  DateFormat: '2 January, 2006'
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: icon.svg
    favicon16x16: icon.svg
    favicon32x32: icon.svg
    apple_touch_icon: icon.svg
    safari_pinned_tab: icon.svg

  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/m-sahebi/'
    - name: github
      url: 'https://github.com/m-sahebi'
    - name: email
      url: 'mailto:msa.prog@gmail.com'

  # analytics:
  #   google:
  #     SiteVerificationTag: ""
  #   bing:
  #     SiteVerificationTag: ""
  #   yandex:
  #     SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    linkFullImages: true

  # editPost:
  #   URL: 'https://github.com/m-sahebi/sahebi.org/content'
  #   Text: 'Suggest Changes' # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    localhost:1313tion: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

googleAnalytics:

outputs:
  home:
    - HTML
    - RSS
    - JSON
